### ISSUE TITLE
Why releases are in the separate repo?

### ISSUE THREAD

**Issue by burner1024** [Project-Epoch/epoch-updater#8]
Not that I'm too worried, but I don't see how this is supposed to assuage anything, if build system is not transparent.
And furthermore, this repo is far behind the "releases" one.

**Comment by kaytotes** [comment]
The repo isn't far behind. You're just looking at the wrong branch. 

Develop is unreleased, main is released.

And its a seperate repo because this one wasn't always open.

**Comment by burner1024** [comment]
OK, so there will a transparent build eventually, correct?
